#!/usr/bin/env bash
# Install nginx on your web-01 server using curl
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw  enable
echo 'Hello World!' > /var/www/html/index.html
service nginx start
