#!/usr/bin/env bash
# Display "Best School" 10 times and displays "Hi" for the 9th iteration

count=0

while [ $count -lt 10 ]; do
      echo "Best School"
      if [ $count -eq 8 ]; then
	  echo "Hi"
      fi
      count=$((count+1))
done
